# SOME DESCRIPTIVE TITLE.
# Copyright (C) 1990-2019, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 2.7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-12-16 18:23+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:3
msgid ":mod:`errno` --- Standard errno system symbols"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:9
msgid "This module makes available standard ``errno`` system symbols. The value of each symbol is the corresponding integer value. The names and descriptions are borrowed from :file:`linux/include/errno.h`, which should be pretty all-inclusive."
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:17
msgid "Dictionary providing a mapping from the errno value to the string name in the underlying system.  For instance, ``errno.errorcode[errno.EPERM]`` maps to ``'EPERM'``."
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:21
msgid "To translate a numeric error code to an error message, use :func:`os.strerror`."
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:23
msgid "Of the following list, symbols that are not used on the current platform are not defined by the module.  The specific list of defined symbols is available as ``errno.errorcode.keys()``.  Symbols available can include:"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:30
msgid "Operation not permitted"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:35
msgid "No such file or directory"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:40
msgid "No such process"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:45
msgid "Interrupted system call"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:50
msgid "I/O error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:55
msgid "No such device or address"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:60
msgid "Arg list too long"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:65
msgid "Exec format error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:70
msgid "Bad file number"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:75
msgid "No child processes"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:80
msgid "Try again"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:85
msgid "Out of memory"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:90
msgid "Permission denied"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:95
msgid "Bad address"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:100
msgid "Block device required"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:105
msgid "Device or resource busy"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:110
msgid "File exists"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:115
msgid "Cross-device link"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:120
msgid "No such device"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:125
msgid "Not a directory"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:130
msgid "Is a directory"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:135
msgid "Invalid argument"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:140
msgid "File table overflow"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:145
msgid "Too many open files"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:150
msgid "Not a typewriter"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:155
msgid "Text file busy"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:160
msgid "File too large"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:165
msgid "No space left on device"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:170
msgid "Illegal seek"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:175
msgid "Read-only file system"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:180
msgid "Too many links"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:185
msgid "Broken pipe"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:190
msgid "Math argument out of domain of func"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:195
msgid "Math result not representable"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:200
msgid "Resource deadlock would occur"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:205
msgid "File name too long"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:210
msgid "No record locks available"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:215
msgid "Function not implemented"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:220
msgid "Directory not empty"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:225
msgid "Too many symbolic links encountered"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:230
msgid "Operation would block"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:235
msgid "No message of desired type"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:240
msgid "Identifier removed"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:245
msgid "Channel number out of range"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:250
msgid "Level 2 not synchronized"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:255
msgid "Level 3 halted"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:260
msgid "Level 3 reset"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:265
msgid "Link number out of range"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:270
msgid "Protocol driver not attached"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:275
msgid "No CSI structure available"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:280
msgid "Level 2 halted"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:285
msgid "Invalid exchange"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:290
msgid "Invalid request descriptor"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:295
msgid "Exchange full"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:300
msgid "No anode"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:305
msgid "Invalid request code"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:310
msgid "Invalid slot"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:315
msgid "File locking deadlock error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:320
msgid "Bad font file format"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:325
msgid "Device not a stream"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:330
msgid "No data available"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:335
msgid "Timer expired"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:340
msgid "Out of streams resources"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:345
msgid "Machine is not on the network"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:350
msgid "Package not installed"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:355
msgid "Object is remote"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:360
msgid "Link has been severed"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:365
msgid "Advertise error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:370
msgid "Srmount error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:375
msgid "Communication error on send"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:380
msgid "Protocol error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:385
msgid "Multihop attempted"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:390
msgid "RFS specific error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:395
msgid "Not a data message"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:400
msgid "Value too large for defined data type"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:405
msgid "Name not unique on network"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:410
msgid "File descriptor in bad state"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:415
msgid "Remote address changed"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:420
msgid "Can not access a needed shared library"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:425
msgid "Accessing a corrupted shared library"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:430
msgid ".lib section in a.out corrupted"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:435
msgid "Attempting to link in too many shared libraries"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:440
msgid "Cannot exec a shared library directly"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:445
msgid "Illegal byte sequence"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:450
msgid "Interrupted system call should be restarted"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:455
msgid "Streams pipe error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:460
msgid "Too many users"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:465
msgid "Socket operation on non-socket"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:470
msgid "Destination address required"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:475
msgid "Message too long"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:480
msgid "Protocol wrong type for socket"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:485
msgid "Protocol not available"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:490
msgid "Protocol not supported"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:495
msgid "Socket type not supported"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:500
msgid "Operation not supported on transport endpoint"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:505
msgid "Protocol family not supported"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:510
msgid "Address family not supported by protocol"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:515
msgid "Address already in use"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:520
msgid "Cannot assign requested address"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:525
msgid "Network is down"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:530
msgid "Network is unreachable"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:535
msgid "Network dropped connection because of reset"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:540
msgid "Software caused connection abort"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:545
msgid "Connection reset by peer"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:550
msgid "No buffer space available"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:555
msgid "Transport endpoint is already connected"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:560
msgid "Transport endpoint is not connected"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:565
msgid "Cannot send after transport endpoint shutdown"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:570
msgid "Too many references: cannot splice"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:575
msgid "Connection timed out"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:580
msgid "Connection refused"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:585
msgid "Host is down"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:590
msgid "No route to host"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:595
msgid "Operation already in progress"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:600
msgid "Operation now in progress"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:605
msgid "Stale NFS file handle"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:610
msgid "Structure needs cleaning"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:615
msgid "Not a XENIX named type file"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:620
msgid "No XENIX semaphores available"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:625
msgid "Is a named type file"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:630
msgid "Remote I/O error"
msgstr ""

#: /home/travis/build/python/cpython-doc-catalog/Doc/library/errno.rst:635
msgid "Quota exceeded"
msgstr ""
