Py_Main() can again be called after Py_Initialize(), as in Python 3.6.
